FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

# 输出静态文件
FROM alpine:3.18
WORKDIR /dist
COPY --from=builder /app/dist .
CMD ["sh", "-c", "cp -r /dist/* /output/"]
